id: A1287D8F0
title: The Twenty-Eight Commitments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:39:22.397448
  last_modified_at: 2022-03-01 05:39:22.397454
