id: A1287D8F0
title: Root Downfalls of the Vajra Vehicle
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:39:22.393103
  last_modified_at: 2022-03-01 05:39:22.393110
